### PR TITLE
Fixed Livy failed to start randomly.

### PR DESCRIPTION
**Pull request by alex-the-man**
Sometimes Livy fails to start with error "Unable to determine spark-submit version(0)".
sparkSubmitVersion() is calling "spark-submit --version" and using LineBufferedProcess to get its console output and parse for the version.
However, LineBufferedProcess has a race condition where LineBufferedProcess.waitFor() doesn't wait for LineBufferedStream to read everything in console output before returning. Hence sometimes LineBufferedStream will not capture the whole output.
In this case, Spark-version will be missing in the caputred output and cause the fatal error "Unable to determine spark-submit version(0)".

Added a fix in LineBufferedProcess.waitFor() to wait for LineBufferedStream to read everything before returning.

### CODE REVIEW

**Comment by alex-the-man** [comment]
I tested the change with commands: watch -n 1 'grep "Warning, livy has not been tested with spark-submit" /var/log/livy/livy.out && rm /var/log/livy/livy.out && restart-livy' and it has been running for 2hrs+ (Livy successfully restarted for at least for 150 times).

**Comment by linchan825** [comment]
Great. Thanks Alex.

Sent from my Windows Phone

**Comment by xinwu246810** [comment]
@tc0312 I solved a problem with your solution! my problem is :

```
[root@master bin]# ./hue livy_server 
SLF4J: Class path contains multiple SLF4J bindings. 
SLF4J: Found binding in [jar:file:/usr/hdp/2.3.2.0-2950/hue/apps/spark/java-lib/livy-assembly.jar!/org/slf4j/impl/StaticLoggerBinder.class] 
SLF4J: Found binding in [jar:file:/usr/hdp/2.3.2.0-2950/hadoop/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class] 
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation. 
Failed to run spark-submit executable: java.io.IOException: Unable to determing spark-submit version [1]: 
```

Now, the Livy server can start! But , When I submit a python file through the Hue Web (Spark Notbook), and excute the python file, have some erros:

```
16/05/05 22:40:11 INFO ServerConnector: Started ServerConnector@4241e0f4{HTTP/1.1}{0.0.0.0:59321}
16/05/05 22:40:11 INFO Server: Started @5841ms
16/05/05 22:40:11 INFO WebServer: Starting server on 59321
Starting livy-repl on http://192.168.0.40:59321
127.0.0.1 - - - 05/May/2016:22:40:32 +0800 "POST /sessions HTTP/1.1" 504 15
127.0.0.1 - - - 05/May/2016:22:42:58 +0800 "GET /sessions HTTP/1.1" 200 1003
127.0.0.1 - - - 05/May/2016:22:43:41 +0800 "POST /sessions HTTP/1.1" 504 15
127.0.0.1 - - - 05/May/2016:22:44:07 +0800 "POST /batches HTTP/1.1" 504 15
127.0.0.1 - - - 05/May/2016:22:44:31 +0800 "POST /batches HTTP/1.1" 504 15
127.0.0.1 - - - 05/May/2016:22:44:37 +0800 "POST /batches HTTP/1.1" 504 15
127.0.0.1 - - - 05/May/2016:22:44:46 +0800 "POST /batches HTTP/1.1" 504 15
```

Could you help me? Thank you !

**Comment by alex-the-man** [comment]
We have moved to a new repo: https://github.com/cloudera/livy
It contains ton of bug fixes and new feature.

**Comment by xinwu246810** [comment]
Thanks for your reply!
I also try the new Livy [ https://github.com/cloudera/livy](url)
But, when I submit a python file through the Hue Web (Spark Notbook), and excute the python file, have some other erros:

```
16/05/05 22:56:44 ERROR SessionServlet$: internal error
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of scala.collection.immutable.List out of VALUE_STRING token
 at [Source: HttpInputOverHTTP@63e8873d; line: 1, column: 19] (through reference chain: com.cloudera.livy.server.batch.CreateBatchRequest["pyFiles"])
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:762)
    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:758)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:275)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:216)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:206)
    at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:76)
    at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:59)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
    at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:238)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2207)
    at com.cloudera.livy.server.JsonServlet.bodyAs(JsonServlet.scala:102)
    at com.cloudera.livy.server.JsonServlet.bodyAs(JsonServlet.scala:98)
    at com.cloudera.livy.server.batch.BatchSessionServlet.createSession(BatchSessionServlet.scala:33)
    at com.cloudera.livy.server.batch.BatchSessionServlet.createSession(BatchSessionServlet.scala:28)
    at com.cloudera.livy.server.SessionServlet$$anonfun$17$$anon$2$$anonfun$18.apply(SessionServlet.scala:127)
    at com.cloudera.livy.server.SessionServlet$$anonfun$17$$anon$2$$anonfun$18.apply(SessionServlet.scala:126)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Could you help me ?

I have another question: whether the Hue can be outside network access ? I worry about the Hue will under attack when outside network access. What do you think?

**Comment by alex-the-man** [comment]
It looks like Hue is not submitting a correct create request to Livy. We are not affiliated with Hue. You might have a better luck asking on Hue's JIRA.

**Comment by xinwu246810** [comment]
Thank you very much for your reply ！

**Pull request closed without merging**
